services:
  api:
    image: payment-gateway:api
    restart: always
    environment:
      ENV: production
      API_PORT: 8080
      DB_URL: ${DB_URL}
      REDIS_URL: redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      JWT_PRIVATE_KEY_PATH: /secrets/jwt_private.pem
      JWT_PUBLIC_KEY_PATH: /secrets/jwt_public.pem
      RATE_LIMIT_PER_MIN: 120
      LOG_SERVICE_NAME: payment-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./dev-certs:/app/dev-certs:ro
      - ./secrets:/secrets:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - payment-network

  postgres:
    image: postgres:13
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - payment-network

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports: []
    networks:
      - payment-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge
