name: Build & Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/paymentgateway
        chmod 600 ~/.ssh/paymentgateway
        ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

    - name: Rsync Project to Droplet
      run: |
        rsync -avz . ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/srv/payment-gateway

    - name: Deploy on Droplet
      run: |
        ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "
          cd /srv/payment-gateway && 
          bash deployments/do/deploy.sh
        "
